
let vectors = [
    { name: 'new1',
      url: 'html/vectors/new1.svg', },
    { name: 'new2',
      url: 'html/vectors/new2.svg', },
    { name: 'new3',
      url: 'html/vectors/new3.svg', },
    { name: 'matthew',
      url: 'html/vectors/matthew.svg', },
    { name: 'bb',
      url: 'html/vectors/bb.svg', },

    { name: 'holepole',
      url: 'html/vectors/holepole.svg', },
      /*
    { name: 'koldat',
      url: 'html/vectors/koldat.svg' },
    { name: 'koldat2',
      url: 'html/vectors/koldat2.svg' },

      { name: 'koldat3',
      url: 'html/vectors/koldat3.svg' },
      { name: 'koldat4',
      url: 'html/vectors/koldat4.svg' },
      { name: 'koldat6',
      url: 'html/vectors/koldat6.svg' },
      { name: 'koldat7',
      url: 'html/vectors/koldat7.svg' },
      { name: 'koldat14',
      url: 'html/vectors/koldat14.svg' },
      { name: 'koldat15',
      url: 'html/vectors/koldat15.svg' },
      { name: 'koldat16',
      url: 'html/vectors/koldat16.svg' },
      { name: 'koldat17',
      url: 'html/vectors/koldat17.svg' },
      { name: 'koldat18',
      url: 'html/vectors/koldat18.svg' },
      { name: 'koldat19',
      url: 'html/vectors/koldat19.svg' },
      { name: 'koldat20',
      url: 'html/vectors/koldat20.svg' },
      { name: 'koldat21',
      url: 'html/vectors/koldat21.svg' },
      { name: 'koldat22',
      url: 'html/vectors/koldat22.svg' },
      { name: 'koldat23',
      url: 'html/vectors/koldat23.svg' },
      { name: 'koldat24',
      url: 'html/vectors/koldat24.svg' },
      { name: 'koldat25',
      url: 'html/vectors/koldat25.svg' },
      { name: 'koldat26',
      url: 'html/vectors/koldat26.svg' },
      */
      { name: 'koldat51',
      url: 'html/vectors/koldat51.svg' },
      /*
      { name: 'koldat52',
      url: 'html/vectors/koldat52.svg' },
      { name: 'koldat53',
      url: 'html/vectors/koldat53.svg' },
      { name: 'koldat54',
      url: 'html/vectors/koldat54.svg' },
      { name: 'koldat55',
      url: 'html/vectors/koldat55.svg' },
      { name: 'koldat56',
      url: 'html/vectors/koldat56.svg' },
      { name: 'koldat57',
      url: 'html/vectors/koldat57.svg' },
      { name: 'koldat58',
      url: 'html/vectors/koldat58.svg' },
      { name: 'koldat59',
      url: 'html/vectors/koldat59.svg' },
      { name: 'koldat60',
      url: 'html/vectors/koldat60.svg' },
      { name: 'koldat61',
      url: 'html/vectors/koldat61.svg' },
      { name: 'koldat62',
      url: 'html/vectors/koldat62.svg' },
      { name: 'koldat63',
      url: 'html/vectors/koldat63.svg' },
      
      { name: 'koldat64',
      url: 'html/vectors/koldat64.svg' },
      */

    { name: 'noobd3v1',
      url: 'html/vectors/noobd3v1.svg' },
    { name: 'noobd3v2',
      url: 'html/vectors/noobd3v2.svg' },

    { name: 'intersecting1',
      url: 'html/vectors/intersection-tests/intersecting1.svg', },
    { name: 'intersecting2',
      url: 'html/vectors/intersection-tests/intersecting2.svg', },
    { name: 'aaa',
      url: 'html/vectors/aaa.svg', },
    { name: 'hat',
      url: 'html/vectors/hat.svg', },
    { name: 'gecko',
      url: 'html/vectors/gecko.svg', },
    { name: 'T2',
      url: 'html/vectors/T2.svg', },
    { name: 'lb',
      url: 'html/vectors/lb.svg', },
    { name: 'ra',
      url: 'html/vectors/ra.svg', },
    { name: 'tt',
      url: 'html/vectors/tt.svg', },
    { name: 'B',
      url: 'html/vectors/B.svg', },
    { name: 'f',
      url: 'html/vectors/f.svg', },
    { name: 'T',
      url: 'html/vectors/T.svg', },
    { name: 'so',
      url: 'html/vectors/so.svg', },
    { name: 'ant',
      url: 'html/vectors/ant.svg', },
    { name: 'bumptube 1',
      url: 'html/vectors/bump_tube1.svg', },
    { name: 'bumptube 2',
      url: 'html/vectors/bump_tube2.svg', },
    { name: 'circle in circle',
      url: 'html/vectors/circle_in_circle.svg', },
    { name: 'circle in square',
      url: 'html/vectors/circle_in_square.svg', },
    { name: 'concave poly',
      url: 'html/vectors/concave_poly.svg', },
    { name: 'hart',
      url: 'html/vectors/hart.svg', },
    { name: 'holy poly',
      url: 'html/vectors/holy_poly.svg', },
    { name: 'intersecting',
      url: 'html/vectors/intersecting.svg', },
    { name: 'play1',
      url: 'html/vectors/play1.svg', },
    { name: 'play2',
      url: 'html/vectors/play2.svg', },
    { name: 'play3',
      url: 'html/vectors/play3.svg', },
    { name: 'poly',
      url: 'html/vectors/poly.svg', },
    { name: 'quad blob',
      url: 'html/vectors/quad_blob.svg', },
    { name: 'simple',
      url: 'html/vectors/simple.svg', },
    { name: 'square in circle',
      url: 'html/vectors/square_in_circle.svg', },
    { name: 'square in square',
      url: 'html/vectors/square_in_square.svg', },
    { name: 'square',
      url: 'html/vectors/square.svg', },
    { name: 'test1',
      url: 'html/vectors/test1.svg', },
    { name: 'test2',
      url: 'html/vectors/test2.svg', },
    { name: 'test3',
      url: 'html/vectors/test3.svg', },
    { name: 'test4',
      url: 'html/vectors/test4.svg', },
    { name: 'two hole',
      url: 'html/vectors/two_hole.svg', },
    { name: 'woodland creatures',
      url: 'html/vectors/woodlancreatures.svg' },    
    { name: 'p1',
      url: 'html/vectors/play/p1.svg' },
    { name: 'p2',
      url: 'html/vectors/play/p2.svg' },
    { name: 'p3',
      url: 'html/vectors/play/p3.svg' },
    { name: 'p4',
      url: 'html/vectors/play/p4.svg' },
    { name: 'poly-04',
      url: 'html/vectors/polys/poly-04.svg' },
    { name: 'poly-11',
      url: 'html/vectors/polys/poly-11.svg' },
    { name: 'poly-12',
      url: 'html/vectors/polys/poly-12.svg' },
    { name: 'poly-121',
      url: 'html/vectors/polys/poly-121.svg' }
];


export { vectors }
