
let vectors = [
    { name: 'O',
      url: 'html/vectors/O.svg', },

    { name: 'a_exclam',
      url: 'html/vectors/allega/exclam.svg', },
    { name: 'notdef',
      url: 'html/vectors/allega/notdef.svg', },

    { name: 'a_ae',
      url: 'html/vectors/allega/ae.svg', },
    { name: 'a_yen',
      url: 'html/vectors/allega/yen.svg', },
    { name: 'a_onehalf',
      url: 'html/vectors/allega/onehalf.svg', },
    { name: 'a_M',
      url: 'html/vectors/allega/M.svg', },
    { name: 'a_Mt',
      url: 'html/vectors/allega/Mt.svg', },
    { name: 'a_Mt2',
      url: 'html/vectors/allega/Mt2.svg', },
    { name: 'a_Mt3',
      url: 'html/vectors/allega/Mt3.svg', },
    { name: 'a_Mt4',
      url: 'html/vectors/allega/Mt4.svg', },
    { name: 'a_Mt5',
      url: 'html/vectors/allega/Mt5.svg', },
    { name: 'a_Mth',
      url: 'html/vectors/allega/Mth.svg', },

    { name: '_A',
      url: 'html/vectors/helvetica/A.svg', },
    { name: '_B',
      url: 'html/vectors/helvetica/B.svg', },
    { name: '_C',
      url: 'html/vectors/helvetica/C.svg', },
    { name: '_D',
      url: 'html/vectors/helvetica/D.svg', },
    { name: '_E',
      url: 'html/vectors/helvetica/E.svg', },

    { name: 'A',
      url: 'html/vectors/A.svg', },
    { name: 'Lamda',
      url: 'html/vectors/Lamda.svg', },
    { name: 'E',
      url: 'html/vectors/E.svg', },
    { name: '3',
      url: 'html/vectors/3.svg' },
    { name: 'S',
      url: 'html/vectors/S.svg' },
    { name: 'P',
      url: 'html/vectors/P.svg', },
    { name: 'china',
      url: 'html/vectors/china.svg', },
    { name: 'china1',
      url: 'html/vectors/china1.svg', },
    { name: 'f',
      url: 'html/vectors/f.svg', },
    { name: 'arab',
      url: 'html/vectors/arab.svg', },

    { name: 'so',
      url: 'html/vectors/so.svg', },

];


export { vectors }
